[package]
name = "ddl"
description = "A binary data definition language"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/yeslogic/ddl"
documentation = "https://docs.rs/ddl"
repository = "https://github.com/yeslogic/ddl"
categories = ["parsing"]
keywords = ["binary", "byte", "parser", "parsing", "endian", "big-endian", "little-endian"]

[dependencies]
Inflector = "0.10.1"
lalrpop-util = "0.13.1"
maplit = "0.1.6"
quote = "0.3.15"
regex = "0.2.0"
unicode-xid = "0.1.0"

[build-dependencies]
lalrpop = "0.13.1"

[dev-dependencies]
difference = "1.0.0"
pretty_assertions = "0.4.0"
